// Generates config/games.php — the full GameDig catalogue the player-counter
// uses to map a Pelican egg to a precise GameDig type + query-port strategy.
//
// Source of truth: the GameDig package bundled in this sidecar
// (node_modules/gamedig/lib/games.js). Re-run after bumping GameDig:
//
//   node sidecar/scripts/generate-catalog.mjs
//
// The output is COMMITTED — production never runs Node to read it. Curated
// overrides (RCON games, EOS, Hytale, hand-tuned match keywords) live in
// config/game-query.php and win over this generated base.

import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'
import { writeFileSync } from 'node:fs'
import { games } from '../node_modules/gamedig/lib/games.js'

const here = dirname(fileURLToPath(import.meta.url))
const outFile = resolve(here, '../../config/games.php')

// GameDig protocol -> our coarse `family`. Only 'eos'/'hytale' change runtime
// behaviour (longer timeout + alternate path in the sidecar); everything else
// is informational, so we collapse it to 'minecraft' or 'other'.
const familyForProtocol = (protocol) => {
  if (protocol === 'minecraft') return 'minecraft'
  return 'other'
}

// Derive query-port strategy relative to the Pelican-allocated GAME port.
// GameDig stores either an offset from the default game port, or an absolute
// query port. See sidecar/node_modules/gamedig/lib/QueryRunner.js for how these
// are consumed when an explicit port is passed.
const portStrategy = (opts) => {
  const offset = opts.port_query_offset
  if (typeof offset === 'number') {
    // GameDig itself adds this offset to the port we pass, so the sidecar path
    // needs no extra offset — but the resulting port must be REACHABLE, which
    // is what the auto-allocation resolver guarantees.
    return offset === 0
      ? { mode: 'same' }
      : { mode: 'offset', value: offset, applied_by_gamedig: true }
  }
  if (typeof opts.port_query === 'number' && typeof opts.port === 'number' && opts.port_query !== opts.port) {
    // Absolute query port unrelated to the game port (e.g. Sons of the Forest:
    // game 8766, query 27016). GameDig only tries it when the passed port equals
    // the game default — which Pelican rarely allocates — so the resolver must
    // allocate this port and point the game's QueryPort variable at it.
    return { mode: 'fixed', value: opts.port_query }
  }
  return { mode: 'same' }
}

// Build match keywords from the human name + any legacy id. The full name is
// specific enough to avoid most false positives ("sons of the forest"); curated
// overrides handle the genuinely ambiguous short names.
const matchKeywords = (id, game) => {
  const set = new Set()
  set.add(game.name.toLowerCase())
  if (game.extra?.old_id) set.add(String(game.extra.old_id).toLowerCase())
  return [...set]
}

const entries = Object.entries(games)
  .map(([id, game]) => {
    const opts = game.options || {}
    return {
      id,
      name: game.name,
      family: familyForProtocol(opts.protocol),
      match: matchKeywords(id, game),
      query_port: portStrategy(opts),
    }
  })
  // Longest name first so specific titles win over generic substrings when the
  // resolver scans in order (first match wins).
  .sort((a, b) => b.name.length - a.name.length)

const phpScalar = (v) => {
  if (typeof v === 'number') return String(v)
  if (typeof v === 'boolean') return v ? 'true' : 'false'
  return "'" + String(v).replace(/\\/g, '\\\\').replace(/'/g, "\\'") + "'"
}

const phpArray = (obj) => {
  const parts = Object.entries(obj).map(([k, v]) => {
    if (Array.isArray(v)) return `'${k}' => [${v.map(phpScalar).join(', ')}]`
    if (v && typeof v === 'object') return `'${k}' => [${Object.entries(v).map(([kk, vv]) => `'${kk}' => ${phpScalar(vv)}`).join(', ')}]`
    return `'${k}' => ${phpScalar(v)}`
  })
  return `[${parts.join(', ')}]`
}

const lines = entries.map((e) => '    '
  + phpArray({ type: e.id, name: e.name, family: e.family, match: e.match, query_port: e.query_port })
  + ',')

const php = `<?php

declare(strict_types=1);

// AUTO-GENERATED by sidecar/scripts/generate-catalog.mjs from GameDig's bundled
// games list. DO NOT EDIT BY HAND — re-run the generator after bumping GameDig.
// Curated overrides (RCON games, EOS, Hytale, hand-tuned keywords) live in
// config/game-query.php and take precedence over this base catalogue.
//
// Each entry:
//   type        : GameDig --type id
//   name        : human label (display only)
//   family      : 'minecraft' | 'other'  (eos/hytale are curated overrides)
//   match       : substrings matched (case-insensitive) against the egg's
//                 "<name> <docker_image> <tags>" — first rule to match wins
//   query_port  : how to reach the A2S/query port relative to the GAME port —
//                 ['mode' => 'same']                          query = game port
//                 ['mode' => 'offset', 'value' => N, ...]     query = game + N
//                 ['mode' => 'fixed',  'value' => P]          query = absolute P
//
// Generated from GameDig ${games['valheim'] ? '' : ''}v5 — ${entries.length} games.
return [
${lines.join('\n')}
];
`

writeFileSync(outFile, php)
console.log(`Wrote ${entries.length} games to ${outFile}`)
