services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mysql
      - redis
    networks:
      - peregrine

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "${DOCKER_APP_PORT:-8080}:80"
    depends_on:
      - app
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - peregrine

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - peregrine

  redis:
    image: redis:alpine
    restart: always
    networks:
      - peregrine

volumes:
  mysql_data:

networks:
  peregrine:
    driver: bridge
