#!/bin/bash
#
# Minecraft: Modpack — Installer
# (c) Damien Rouge / rouge-informatique.ch — License: MIT
#
# Universal Minecraft modpack installer. Authored from scratch from the public
# marketplace docs; not derived from any third-party installer. Runs inside the
# Pelican install container with /mnt/server bound as the working directory.
#
# Required env vars (injected by the plugin through the egg variables):
#   BB_MODPACK_PROVIDER       modrinth | curseforge | atlauncher | ftb | technic | voidswrath
#   BB_MODPACK_ID             provider-side modpack identifier
#   BB_MODPACK_VERSION_ID     provider-side version identifier
#   BB_MODPACK_GAME_VERSION   minecraft version hint (optional)
#   BB_MODPACK_PURGE          1 to wipe /mnt/server before installing
#   BB_MODPACK_CURSEFORGE_KEY CurseForge API key (only used by the curseforge provider)
#   SERVER_JARFILE            target jar filename (the script symlinks server.jar to whatever it finds)

set -uo pipefail

WORKDIR="/mnt/server"
TMPDIR="/tmp/bb-modpack-$$"
USER_AGENT="PeregrineModpackInstaller/1.0 (+https://games.biomebounty.com)"

log()  { printf '[modpack-installer] %s\n' "$*"; }
warn() { printf '[modpack-installer] WARN: %s\n' "$*" >&2; }
fail() { printf '[modpack-installer] FATAL: %s\n' "$*" >&2; exit 1; }

cleanup() { rm -rf "$TMPDIR" 2>/dev/null || true; }
trap cleanup EXIT

# ---------------------------------------------------------------------------
# Setup
# ---------------------------------------------------------------------------

ensure_tools() {
    log "Installing required tools (curl, unzip, jq, tar, ca-certificates)."
    apt-get update -y >/dev/null 2>&1 || warn "apt-get update returned non-zero (best effort)"
    apt-get install -y --no-install-recommends \
        curl unzip jq tar ca-certificates xz-utils file >/dev/null 2>&1 \
        || fail "unable to install required tools"

    for bin in curl unzip jq tar; do
        command -v "$bin" >/dev/null 2>&1 || fail "missing required tool: $bin"
    done
}

# Args: <url> <output-file> [optional auth header].
http_download() {
    local url="$1" out="$2" header="${3:-}" attempt rc
    for attempt in 1 2 3; do
        if [ -n "$header" ]; then
            curl -fL --retry 0 --connect-timeout 30 --max-time 600 \
                -H "User-Agent: $USER_AGENT" -H "$header" \
                -o "$out" "$url"
        else
            curl -fL --retry 0 --connect-timeout 30 --max-time 600 \
                -H "User-Agent: $USER_AGENT" \
                -o "$out" "$url"
        fi
        rc=$?
        if [ "$rc" -eq 0 ]; then
            return 0
        fi
        warn "download attempt $attempt failed (curl rc=$rc) — $url"
        sleep $((attempt * 3))
    done
    return 1
}

http_get() {
    local url="$1" header="${2:-}" attempt rc body
    for attempt in 1 2 3; do
        if [ -n "$header" ]; then
            body=$(curl -fsSL --retry 0 --connect-timeout 30 --max-time 60 \
                -H "User-Agent: $USER_AGENT" -H "$header" "$url")
        else
            body=$(curl -fsSL --retry 0 --connect-timeout 30 --max-time 60 \
                -H "User-Agent: $USER_AGENT" "$url")
        fi
        rc=$?
        if [ "$rc" -eq 0 ]; then
            printf '%s' "$body"
            return 0
        fi
        warn "http_get attempt $attempt failed (rc=$rc) — $url"
        sleep $((attempt * 2))
    done
    return 1
}

http_post_json() {
    local url="$1" body="$2" header="${3:-}" attempt rc resp
    for attempt in 1 2 3; do
        if [ -n "$header" ]; then
            resp=$(curl -fsSL --retry 0 --connect-timeout 30 --max-time 60 \
                -H "User-Agent: $USER_AGENT" -H "$header" \
                -H 'Content-Type: application/json' \
                -d "$body" "$url")
        else
            resp=$(curl -fsSL --retry 0 --connect-timeout 30 --max-time 60 \
                -H "User-Agent: $USER_AGENT" \
                -H 'Content-Type: application/json' \
                -d "$body" "$url")
        fi
        rc=$?
        if [ "$rc" -eq 0 ]; then
            printf '%s' "$resp"
            return 0
        fi
        warn "http_post_json attempt $attempt failed (rc=$rc) — $url"
        sleep $((attempt * 2))
    done
    return 1
}

prepare_workdir() {
    mkdir -p "$WORKDIR"
    cd "$WORKDIR" || fail "cannot cd $WORKDIR"

    if [ "${BB_MODPACK_PURGE:-1}" = "1" ]; then
        log "Wiping server directory."
        find . -mindepth 1 -delete 2>/dev/null || true
    fi

    mkdir -p "$TMPDIR"
}

write_eula() {
    cat > "$WORKDIR/eula.txt" <<'EOF'
# Auto-generated by the Modpack Installer plugin.
# By accepting this EULA you confirm the player accepted Mojang's EULA at
# https://account.mojang.com/documents/minecraft_eula
eula=true
EOF
}

# Heuristic: find a likely server jar in $WORKDIR and symlink server.jar to it.
finalize_jar() {
    cd "$WORKDIR" || return 1

    if [ -f "server.jar" ]; then
        log "server.jar already in place."
        return 0
    fi

    local candidate=""
    local pattern
    for pattern in \
        "neoforge-*-universal.jar" \
        "neoforge-*-server.jar" \
        "neoforge-*.jar" \
        "forge-*-universal.jar" \
        "forge-*-server.jar" \
        "fabric-server-launch.jar" \
        "fabric-server-mc*.jar" \
        "quilt-server-launch.jar" \
        "quilt-server-launcher.jar" \
        "minecraft_server.*.jar" \
        "paper-*.jar" \
        "purpur-*.jar" \
        "*.jar"
    do
        candidate=$(find "$WORKDIR" -maxdepth 2 -type f -name "$pattern" 2>/dev/null | head -n1)
        [ -n "$candidate" ] && break
    done

    if [ -z "$candidate" ]; then
        warn "no candidate jar found under $WORKDIR — server.jar not created"
        return 1
    fi

    log "Symlinking server.jar -> $(basename "$candidate")"
    ln -sf "$(realpath --relative-to="$WORKDIR" "$candidate")" "$WORKDIR/server.jar"
}

# ---------------------------------------------------------------------------
# Provider: Modrinth — https://docs.modrinth.com/api/operations/getversion/
# ---------------------------------------------------------------------------
install_modrinth() {
    log "Provider: Modrinth — version $BB_MODPACK_VERSION_ID"

    local version_json files_count primary_url primary_filename
    version_json=$(http_get "https://api.modrinth.com/v2/version/$BB_MODPACK_VERSION_ID") \
        || fail "failed to fetch Modrinth version metadata"

    files_count=$(echo "$version_json" | jq '.files | length')
    [ "$files_count" -gt 0 ] || fail "Modrinth version has no files"

    primary_url=$(echo "$version_json" | jq -r '(.files[] | select(.primary == true) | .url) // .files[0].url')
    primary_filename=$(echo "$version_json" | jq -r '(.files[] | select(.primary == true) | .filename) // .files[0].filename')
    [ -n "$primary_url" ] && [ "$primary_url" != "null" ] || fail "Modrinth primary file URL missing"

    log "Downloading $primary_filename"
    http_download "$primary_url" "$TMPDIR/$primary_filename" \
        || fail "Modrinth pack download failed"

    case "$primary_filename" in
        *.mrpack)  install_modrinth_mrpack "$TMPDIR/$primary_filename" ;;
        *.zip)     log "Extracting zip into $WORKDIR" ; unzip -qo "$TMPDIR/$primary_filename" -d "$WORKDIR" || fail "unzip failed" ;;
        *.jar)     log "Direct jar — installing as $primary_filename" ; cp "$TMPDIR/$primary_filename" "$WORKDIR/$primary_filename" ;;
        *)         warn "unrecognized Modrinth artifact: $primary_filename — copying raw" ; cp "$TMPDIR/$primary_filename" "$WORKDIR/$primary_filename" ;;
    esac
}

# .mrpack format: zip with modrinth.index.json describing files{} (downloads from
# external URLs, write to path) and an overrides/ directory copied as-is.
install_modrinth_mrpack() {
    local pack="$1"
    local extract="$TMPDIR/mrpack"

    log "Extracting .mrpack manifest"
    mkdir -p "$extract"
    unzip -qo "$pack" -d "$extract" || fail "mrpack extract failed"

    [ -f "$extract/modrinth.index.json" ] || fail "modrinth.index.json missing in mrpack"

    if [ -d "$extract/overrides" ]; then
        log "Copying overrides/"
        cp -rT "$extract/overrides" "$WORKDIR"
    fi
    if [ -d "$extract/server-overrides" ]; then
        log "Copying server-overrides/"
        cp -rT "$extract/server-overrides" "$WORKDIR"
    fi

    local total resolved index
    total=$(jq '.files | length' "$extract/modrinth.index.json")
    log "Resolving $total external file(s) declared in modrinth.index.json"
    resolved=0

    for index in $(seq 0 $((total - 1))); do
        local entry path url server_env
        entry=$(jq -c ".files[$index]" "$extract/modrinth.index.json")
        path=$(echo "$entry" | jq -r '.path')
        url=$(echo "$entry" | jq -r '.downloads[0]')
        server_env=$(echo "$entry" | jq -r '.env.server // "required"')

        if [ "$server_env" = "unsupported" ]; then
            continue
        fi

        local outpath="$WORKDIR/$path"
        mkdir -p "$(dirname "$outpath")"
        if http_download "$url" "$outpath"; then
            resolved=$((resolved + 1))
        else
            warn "failed to download $path (continuing)"
        fi
    done
    log "Resolved $resolved/$total file(s)"

    local mc forge fabric quilt neoforge
    mc=$(jq -r '.dependencies.minecraft // ""' "$extract/modrinth.index.json")
    forge=$(jq -r '.dependencies["forge"] // ""' "$extract/modrinth.index.json")
    neoforge=$(jq -r '.dependencies["neoforge"] // ""' "$extract/modrinth.index.json")
    fabric=$(jq -r '.dependencies["fabric-loader"] // ""' "$extract/modrinth.index.json")
    quilt=$(jq -r '.dependencies["quilt-loader"] // ""' "$extract/modrinth.index.json")

    if [ -n "$forge" ] && [ -n "$mc" ]; then
        install_forge "$mc" "$forge"
    elif [ -n "$neoforge" ] && [ -n "$mc" ]; then
        install_neoforge "$mc" "$neoforge"
    elif [ -n "$fabric" ] && [ -n "$mc" ]; then
        install_fabric "$mc" "$fabric"
    elif [ -n "$quilt" ] && [ -n "$mc" ]; then
        install_quilt "$mc" "$quilt"
    elif [ -n "$mc" ]; then
        install_vanilla "$mc"
    else
        warn "no loader dependency declared in mrpack — leaving server jar to manual placement"
    fi
}

# ---------------------------------------------------------------------------
# Provider: CurseForge — https://docs.curseforge.com/rest-api/
# ---------------------------------------------------------------------------
install_curseforge() {
    log "Provider: CurseForge — mod $BB_MODPACK_ID, file $BB_MODPACK_VERSION_ID"
    [ -n "${BB_MODPACK_CURSEFORGE_KEY:-}" ] || fail "CurseForge API key missing — operator must set it in /admin/modpack-settings"

    local hdr="x-api-key: $BB_MODPACK_CURSEFORGE_KEY"
    local file_json server_pack_id download_url file_name is_server_pack

    file_json=$(http_get "https://api.curseforge.com/v1/mods/$BB_MODPACK_ID/files/$BB_MODPACK_VERSION_ID" "$hdr") \
        || fail "failed to fetch CurseForge file metadata"

    is_server_pack=$(echo "$file_json" | jq -r '.data.isServerPack // false')
    server_pack_id=$(echo "$file_json" | jq -r '.data.serverPackFileId // empty')

    if [ "$is_server_pack" != "true" ] && [ -n "$server_pack_id" ]; then
        log "Modpack file points at server pack $server_pack_id — fetching that."
        file_json=$(http_get "https://api.curseforge.com/v1/mods/$BB_MODPACK_ID/files/$server_pack_id" "$hdr") \
            || fail "failed to fetch CurseForge server-pack file"
        is_server_pack="true"
    fi

    download_url=$(echo "$file_json" | jq -r '.data.downloadUrl // empty')
    file_name=$(echo "$file_json" | jq -r '.data.fileName // "modpack.zip"')

    if [ -z "$download_url" ]; then
        local file_id_str padded
        file_id_str=$(echo "$file_json" | jq -r '.data.id')
        padded=$(printf '%07d' "$file_id_str")
        download_url="https://edge.forgecdn.net/files/${padded:0:4}/${padded:4}/$file_name"
        warn "downloadUrl null; reconstructed CDN URL: $download_url"
    fi

    log "Downloading $file_name"
    http_download "$download_url" "$TMPDIR/$file_name" "$hdr" \
        || fail "CurseForge download failed"

    if [ "$is_server_pack" = "true" ]; then
        log "Extracting server-pack zip into $WORKDIR"
        unzip -qo "$TMPDIR/$file_name" -d "$WORKDIR" || fail "unzip failed"
        if [ -f "$WORKDIR/startserver.sh" ]; then
            log "Running provided startserver.sh (best effort, may exit early once jar is built)."
            chmod +x "$WORKDIR/startserver.sh" 2>/dev/null
            (cd "$WORKDIR" && timeout 300 bash startserver.sh nogui 2>&1 | head -n 200) || true
        fi
    else
        install_curseforge_manifest "$TMPDIR/$file_name" "$hdr"
    fi
}

install_curseforge_manifest() {
    local pack="$1" hdr="$2"
    local extract="$TMPDIR/cfpack"

    mkdir -p "$extract"
    unzip -qo "$pack" -d "$extract" || fail "extract cfpack failed"
    [ -f "$extract/manifest.json" ] || fail "manifest.json missing in CurseForge pack"

    if [ -d "$extract/overrides" ]; then
        log "Copying overrides/"
        cp -rT "$extract/overrides" "$WORKDIR"
    fi

    local mc loader_id
    mc=$(jq -r '.minecraft.version' "$extract/manifest.json")
    loader_id=$(jq -r '.minecraft.modLoaders[] | select(.primary == true) | .id // empty' "$extract/manifest.json")

    local total index
    total=$(jq '.files | length' "$extract/manifest.json")
    log "Resolving $total mod file(s) from CurseForge manifest"
    mkdir -p "$WORKDIR/mods"
    for index in $(seq 0 $((total - 1))); do
        local pid fid file_meta dl filename
        pid=$(jq -r ".files[$index].projectID" "$extract/manifest.json")
        fid=$(jq -r ".files[$index].fileID" "$extract/manifest.json")

        file_meta=$(http_get "https://api.curseforge.com/v1/mods/$pid/files/$fid" "$hdr") || continue
        dl=$(echo "$file_meta" | jq -r '.data.downloadUrl // empty')
        filename=$(echo "$file_meta" | jq -r '.data.fileName // empty')

        if [ -z "$dl" ]; then
            local file_id_str padded
            file_id_str=$(echo "$file_meta" | jq -r '.data.id')
            padded=$(printf '%07d' "$file_id_str")
            dl="https://edge.forgecdn.net/files/${padded:0:4}/${padded:4}/$filename"
        fi

        http_download "$dl" "$WORKDIR/mods/$filename" || warn "failed mod $filename (continuing)"
    done

    case "$loader_id" in
        forge-*)    install_forge "$mc" "${loader_id#forge-}" ;;
        neoforge-*) install_neoforge "$mc" "${loader_id#neoforge-}" ;;
        fabric-*)   install_fabric "$mc" "${loader_id#fabric-}" ;;
        quilt-*)    install_quilt "$mc" "${loader_id#quilt-}" ;;
        *)          warn "unknown CurseForge loader id: $loader_id (running vanilla $mc)" ; install_vanilla "$mc" ;;
    esac
}

# ---------------------------------------------------------------------------
# Provider: ATLauncher — https://wiki.atlauncher.com/api-docs/v2/
# ---------------------------------------------------------------------------
install_atlauncher() {
    log "Provider: ATLauncher — pack $BB_MODPACK_ID, version $BB_MODPACK_VERSION_ID"

    local query
    query=$(jq -nc \
        --arg safe "$BB_MODPACK_ID" \
        '{ query: "query($safe: String!) { packBySafeName(safeName: $safe) { id safeName name versions { version minecraftVersion } } }", variables: { safe: $safe } }')
    local resp
    resp=$(http_post_json "https://api.atlauncher.com/v2/graphql" "$query") \
        || fail "ATLauncher GraphQL request failed"

    local pack_id
    pack_id=$(echo "$resp" | jq -r '.data.packBySafeName.id // empty')
    [ -n "$pack_id" ] || fail "ATLauncher pack '$BB_MODPACK_ID' not found"

    # ATLauncher hosts the per-version JSON manifest on a CDN. The launcher's
    # canonical CDN host is `download.nodecdn.net/containers/atl/...` but the
    # public V2 docs do not formally pin the per-version path. Try the nodecdn
    # path first (matches what the official launcher fetches), then fall back
    # to the legacy `download.atlauncher.com` host. If both fail, surface the
    # failure clearly — install cannot proceed without the manifest.
    local manifest=""
    local manifest_urls=(
        "https://download.nodecdn.net/containers/atl/launcher/json/packs/$BB_MODPACK_ID/versions/$BB_MODPACK_VERSION_ID.json"
        "https://download.atlauncher.com/json/packs/$BB_MODPACK_ID/versions/$BB_MODPACK_VERSION_ID.json"
    )
    for manifest_url in "${manifest_urls[@]}"; do
        log "Trying ATLauncher manifest: $manifest_url"
        if manifest=$(http_get "$manifest_url") && [ -n "$manifest" ]; then
            break
        fi
        manifest=""
    done
    [ -n "$manifest" ] || fail "ATLauncher version manifest unreachable on every known CDN"

    local mc loader_type loader_version
    mc=$(echo "$manifest" | jq -r '.minecraft // ""')
    loader_type=$(echo "$manifest" | jq -r '.loader.type // ""')
    loader_version=$(echo "$manifest" | jq -r '.loader.version // ""')

    local total index
    total=$(echo "$manifest" | jq '.mods | length // 0')
    mkdir -p "$WORKDIR/mods"
    for index in $(seq 0 $((total - 1))); do
        local entry side url filename
        entry=$(echo "$manifest" | jq -c ".mods[$index]")
        side=$(echo "$entry" | jq -r '.side // "both"')
        if [ "$side" = "client" ]; then continue; fi
        url=$(echo "$entry" | jq -r '.url // ""')
        filename=$(echo "$entry" | jq -r '.file // ""')
        if [ -z "$url" ] || [ -z "$filename" ]; then continue; fi
        http_download "$url" "$WORKDIR/mods/$filename" || warn "failed mod $filename"
    done

    local cfg_url
    cfg_url=$(echo "$manifest" | jq -r '.configs.url // ""')
    if [ -n "$cfg_url" ]; then
        http_download "$cfg_url" "$TMPDIR/configs.zip" \
            && unzip -qo "$TMPDIR/configs.zip" -d "$WORKDIR" \
            || warn "config bundle failed"
    fi

    case "$loader_type" in
        forge)    install_forge "$mc" "$loader_version" ;;
        neoforge) install_neoforge "$mc" "$loader_version" ;;
        fabric)   install_fabric "$mc" "$loader_version" ;;
        quilt)    install_quilt "$mc" "$loader_version" ;;
        *)        install_vanilla "$mc" ;;
    esac
}

# ---------------------------------------------------------------------------
# Provider: Feed The Beast — https://modpacksch.docs.apiary.io/
# ---------------------------------------------------------------------------
install_ftb() {
    log "Provider: FTB — pack $BB_MODPACK_ID, version $BB_MODPACK_VERSION_ID"

    local server_resp server_url
    server_resp=$(http_get "https://api.modpacks.ch/public/modpack/$BB_MODPACK_ID/$BB_MODPACK_VERSION_ID/server/linux") || true
    server_url=$(echo "$server_resp" | jq -r '.message // empty')
    case "$server_url" in
        http*)
            log "Downloading FTB pre-built server bundle"
            http_download "$server_url" "$TMPDIR/ftb-server.tar.gz" || fail "FTB server bundle download failed"
            if file "$TMPDIR/ftb-server.tar.gz" | grep -qi 'gzip'; then
                tar -xzf "$TMPDIR/ftb-server.tar.gz" -C "$WORKDIR"
            else
                unzip -qo "$TMPDIR/ftb-server.tar.gz" -d "$WORKDIR" || true
            fi
            if [ -f "$WORKDIR/serverinstall_linux" ]; then
                chmod +x "$WORKDIR/serverinstall_linux" 2>/dev/null
                (cd "$WORKDIR" && timeout 600 bash serverinstall_linux 2>&1 | head -n 200) || true
            fi
            return 0
            ;;
    esac

    log "Server bundle not available, installing files individually."
    local manifest manifest_status
    manifest=$(http_get "https://api.modpacks.ch/public/modpack/$BB_MODPACK_ID/$BB_MODPACK_VERSION_ID") \
        || fail "FTB manifest fetch failed"

    # FTB returns 200 OK with `{"status":"error","message":"..."}` on bad
    # IDs / unknown versions instead of a 4xx — must inspect the envelope.
    manifest_status=$(echo "$manifest" | jq -r '.status // "ok"')
    if [ "$manifest_status" = "error" ]; then
        fail "FTB manifest error: $(echo "$manifest" | jq -r '.message // "unknown"')"
    fi

    local total index
    total=$(echo "$manifest" | jq '.files | length // 0')
    [ "$total" -gt 0 ] || fail "FTB version has no files"
    log "Downloading $total file(s)"
    for index in $(seq 0 $((total - 1))); do
        local entry url path clientonly fullpath
        entry=$(echo "$manifest" | jq -c ".files[$index]")
        url=$(echo "$entry" | jq -r '.url')
        path=$(echo "$entry" | jq -r '(.path // "/") + (.name // "")')
        clientonly=$(echo "$entry" | jq -r '.clientonly // false')
        if [ "$clientonly" = "true" ]; then continue; fi
        fullpath="$WORKDIR/$path"
        mkdir -p "$(dirname "$fullpath")"
        http_download "$url" "$fullpath" || warn "failed: $path"
    done

    local mc loader_type loader_version
    mc=$(echo "$manifest" | jq -r '.targets[] | select(.name == "minecraft") | .version // ""' | head -n1)
    for loader_type in forge neoforge fabric quilt; do
        loader_version=$(echo "$manifest" | jq -r ".targets[] | select(.name == \"$loader_type\") | .version // empty" | head -n1)
        if [ -n "$loader_version" ]; then
            "install_$loader_type" "$mc" "$loader_version"
            return 0
        fi
    done
    install_vanilla "$mc"
}

# ---------------------------------------------------------------------------
# Provider: Technic — https://gist.github.com/EpicKiwi/e91483132ded278b49dbd88c675f0b14
# ---------------------------------------------------------------------------
install_technic() {
    log "Provider: Technic — slug $BB_MODPACK_ID, build $BB_MODPACK_VERSION_ID"

    local launcher_build pack solder build_data zip_url
    launcher_build=$(http_get "https://api.technicpack.net/launcher/version/stable4" 2>/dev/null \
        | jq -r '.build // empty') || true
    [ -n "$launcher_build" ] || launcher_build="746"

    pack=$(http_get "https://api.technicpack.net/modpack/$BB_MODPACK_ID?build=$launcher_build") \
        || fail "Technic pack lookup failed"
    solder=$(echo "$pack" | jq -r '.solder // empty')

    if [ -n "$solder" ] && [ "$solder" != "null" ]; then
        build_data=$(http_get "$solder/modpack/$BB_MODPACK_ID/$BB_MODPACK_VERSION_ID") \
            || fail "Technic Solder build fetch failed"
        local total index
        total=$(echo "$build_data" | jq '.mods | length // 0')
        log "Downloading $total mod archive(s) from Technic Solder"
        for index in $(seq 0 $((total - 1))); do
            local mod_url filename
            mod_url=$(echo "$build_data" | jq -r ".mods[$index].url")
            filename=$(echo "$build_data" | jq -r ".mods[$index].name").zip
            http_download "$mod_url" "$TMPDIR/$filename" || continue
            unzip -qo "$TMPDIR/$filename" -d "$WORKDIR" || true
        done
        local mc forge_version
        mc=$(echo "$build_data" | jq -r '.minecraft // ""')
        forge_version=$(echo "$build_data" | jq -r '.forge // ""')
        if [ -n "$forge_version" ] && [ "$forge_version" != "null" ]; then
            install_forge "$mc" "$forge_version"
        else
            install_vanilla "$mc"
        fi
    else
        zip_url=$(echo "$pack" | jq -r '.url // empty')
        [ -n "$zip_url" ] && [ "$zip_url" != "null" ] || fail "Technic non-Solder pack URL missing"
        log "Downloading flat Technic pack zip"
        http_download "$zip_url" "$TMPDIR/technic-pack.zip" || fail "Technic pack download failed"
        unzip -qo "$TMPDIR/technic-pack.zip" -d "$WORKDIR" || fail "unzip failed"
    fi
}

# ---------------------------------------------------------------------------
# Provider: VoidsWrath — community catalog mirror
# ---------------------------------------------------------------------------
install_voidswrath() {
    log "Provider: VoidsWrath — id $BB_MODPACK_ID"

    local catalog entry server_url
    catalog=$(http_get "https://raw.githubusercontent.com/astrooom/minecraft-modpack-index/main/voidswrath-modpacks.json") \
        || fail "VoidsWrath catalog fetch failed"

    entry=$(echo "$catalog" | jq -c "first(.[] | select((.id|tostring) == \"$BB_MODPACK_ID\"))")
    [ -n "$entry" ] && [ "$entry" != "null" ] || fail "VoidsWrath modpack '$BB_MODPACK_ID' not in catalog"

    server_url=$(echo "$entry" | jq -r '.serverPackUrl // empty')
    [ -n "$server_url" ] && [ "$server_url" != "null" ] || fail "VoidsWrath modpack has no serverPackUrl"

    log "Downloading VoidsWrath server pack"
    http_download "$server_url" "$TMPDIR/voids.zip" || fail "VoidsWrath download failed"
    unzip -qo "$TMPDIR/voids.zip" -d "$WORKDIR" || fail "unzip failed"
}

# ---------------------------------------------------------------------------
# Loader installers — vanilla / Forge / NeoForge / Fabric / Quilt
# ---------------------------------------------------------------------------
install_vanilla() {
    local mc="$1"
    [ -n "$mc" ] || { warn "install_vanilla: no mc version"; return; }
    log "Installing vanilla Minecraft server $mc"
    local manifest version_url server_url
    manifest=$(http_get "https://launchermeta.mojang.com/mc/game/version_manifest_v2.json") || return
    version_url=$(echo "$manifest" | jq -r --arg v "$mc" '.versions[] | select(.id == $v) | .url' | head -n1)
    [ -n "$version_url" ] || { warn "vanilla manifest: $mc not found"; return; }
    local version_meta
    version_meta=$(http_get "$version_url") || return
    server_url=$(echo "$version_meta" | jq -r '.downloads.server.url // empty')
    [ -n "$server_url" ] && [ "$server_url" != "null" ] || { warn "no server.jar URL for $mc"; return; }
    http_download "$server_url" "$WORKDIR/server.jar" || warn "vanilla server jar download failed"
}

install_forge() {
    local mc="$1" forge="$2"
    [ -n "$mc" ] && [ -n "$forge" ] || { warn "install_forge: missing args"; return; }
    log "Installing Forge $forge for $mc"
    local installer_url installer
    installer_url="https://maven.minecraftforge.net/net/minecraftforge/forge/${mc}-${forge}/forge-${mc}-${forge}-installer.jar"
    installer="$TMPDIR/forge-installer.jar"
    if ! http_download "$installer_url" "$installer"; then
        warn "Forge installer download failed (URL: $installer_url) — trying fallback"
        installer_url="https://maven.minecraftforge.net/net/minecraftforge/forge/${mc}-${forge}-${mc}/forge-${mc}-${forge}-${mc}-installer.jar"
        http_download "$installer_url" "$installer" || { warn "Forge installer unreachable"; return; }
    fi
    (cd "$WORKDIR" && timeout 600 java -jar "$installer" --installServer 2>&1 | tail -n 30) \
        || warn "Forge installer returned non-zero (jar may still be usable)"
}

install_neoforge() {
    local mc="$1" neo="$2"
    log "Installing NeoForge $neo for $mc"
    local url installer
    url="https://maven.neoforged.net/releases/net/neoforged/neoforge/${neo}/neoforge-${neo}-installer.jar"
    installer="$TMPDIR/neoforge-installer.jar"
    http_download "$url" "$installer" || { warn "NeoForge installer unreachable"; return; }
    (cd "$WORKDIR" && timeout 600 java -jar "$installer" --installServer 2>&1 | tail -n 30) \
        || warn "NeoForge installer returned non-zero"
}

install_fabric() {
    local mc="$1" fab="$2"
    log "Installing Fabric loader $fab for $mc"
    local installer_meta installer_version url
    installer_meta=$(http_get "https://meta.fabricmc.net/v2/versions/installer") || return
    installer_version=$(echo "$installer_meta" | jq -r '.[0].version')
    url="https://meta.fabricmc.net/v2/versions/loader/${mc}/${fab}/${installer_version}/server/jar"
    http_download "$url" "$WORKDIR/fabric-server-launch.jar" \
        || warn "Fabric server jar download failed"
}

install_quilt() {
    local mc="$1" quilt="$2"
    log "Installing Quilt loader $quilt for $mc"
    local installer="$TMPDIR/quilt-installer.jar"
    http_download "https://quiltmc.org/api/v1/download-latest-installer/java-universal" "$installer" \
        || { warn "Quilt installer unreachable"; return; }
    (cd "$WORKDIR" && timeout 600 java -jar "$installer" install server "$mc" "$quilt" --download-server --install-dir="$WORKDIR" 2>&1 | tail -n 30) \
        || warn "Quilt installer returned non-zero"
}

# ---------------------------------------------------------------------------
# Uninstall mode — wipe /mnt/server clean. The plugin then swaps the server
# back to the original egg with skip_scripts=false to let it install from
# scratch on an empty directory. Phase 1 of the two-phase uninstall flow.
# ---------------------------------------------------------------------------
uninstall_modpack() {
    log "Uninstall mode — wiping $WORKDIR"

    mkdir -p "$WORKDIR"
    cd "$WORKDIR" || fail "cannot cd $WORKDIR"

    # Delete every file/dir at the root of /mnt/server. -mindepth 1 keeps
    # the mountpoint itself intact so Wings doesn't lose the volume.
    find . -mindepth 1 -delete 2>/dev/null || true

    # Pelican expects an install completion signal — a successful exit is
    # enough; no placeholder files needed because the next phase (original
    # egg reinstall) will repopulate the directory from scratch.
    log "Uninstall complete — directory wiped"
    exit 0
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
main() {
    log "Modpack Installer starting (operation=${BB_MODPACK_OPERATION:-install})"

    if [ "${BB_MODPACK_OPERATION:-install}" = "uninstall" ]; then
        uninstall_modpack
    fi

    : "${BB_MODPACK_PROVIDER:?provider not set}"
    : "${BB_MODPACK_ID:?modpack id not set}"
    : "${BB_MODPACK_VERSION_ID:?version id not set}"

    ensure_tools
    prepare_workdir

    case "$BB_MODPACK_PROVIDER" in
        modrinth)   install_modrinth ;;
        curseforge) install_curseforge ;;
        atlauncher) install_atlauncher ;;
        ftb)        install_ftb ;;
        technic)    install_technic ;;
        voidswrath) install_voidswrath ;;
        *) fail "unknown provider: $BB_MODPACK_PROVIDER" ;;
    esac

    write_eula
    finalize_jar || warn "server.jar finalization incomplete — manual placement may be needed"

    log "Modpack installation complete"
    exit 0
}

main "$@"
