<?php

namespace App\Filament\Resources;

use App\Filament\Resources\PelicanWebhookLogResource\Pages;
use App\Models\PelicanProcessedEvent;
use BackedEnum;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use UnitEnum;
use Filament\Actions\Action;
use Illuminate\Support\HtmlString;

/**
 * Read-only audit page for Pelican outgoing webhooks Peregrine has accepted.
 * One row per event, with idempotency hash, model id, response status, and
 * any handler error.
 *
 * Hidden when the Pelican webhook receiver is disabled (the toggle in
 * /admin/pelican-webhook-settings) — these rows are only generated by that
 * receiver, so the page would always be empty.
 */
class PelicanWebhookLogResource extends Resource
{
    protected static ?string $model = PelicanProcessedEvent::class;

    protected static string|BackedEnum|null $navigationIcon = 'heroicon-o-clipboard-document-list';

    protected static ?int $navigationSort = 31;

    public static function getNavigationGroup(): ?string
    {
        return 'Integrations';
    }

    public static function getNavigationLabel(): string
    {
        return __('admin.resources.pelican_webhook_logs.navigation');
    }

    public static function getModelLabel(): string
    {
        return __('admin.resources.pelican_webhook_logs.label');
    }

    public static function getPluralModelLabel(): string
    {
        return __('admin.resources.pelican_webhook_logs.plural');
    }

    public static function shouldRegisterNavigation(): bool
    {
        $value = (string) app(\App\Services\SettingsService::class)
            ->get('pelican_webhook_enabled', 'false');

        return $value === 'true' || $value === '1';
    }

    public static function canCreate(): bool
    {
        return false;
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('processed_at')
                    ->dateTime()
                    ->sortable()
                    ->label('When'),
                Tables\Columns\TextColumn::make('event_type')
                    ->label('Event')
                    ->wrap()
                    ->searchable(),
                Tables\Columns\TextColumn::make('pelican_model_id')
                    ->label('Pelican ID')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('response_status')
                    ->label('HTTP')
                    ->badge()
                    ->color(fn (int $state): string => match (true) {
                        $state >= 500 => 'danger',
                        $state >= 400 => 'warning',
                        $state >= 200 && $state < 300 => 'success',
                        default => 'gray',
                    })
                    ->sortable(),
                Tables\Columns\TextColumn::make('error_message')
                    ->label('Error')
                    ->limit(60)
                    ->placeholder('—')
                    ->tooltip(fn ($state): ?string => $state),
                Tables\Columns\TextColumn::make('idempotency_hash')
                    ->label('Hash')
                    ->limit(12)
                    ->tooltip(fn ($state): ?string => $state)
                    ->copyable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                Tables\Filters\SelectFilter::make('event_type')
                    ->label('Event type')
                    ->options(fn () => PelicanProcessedEvent::query()
                        ->distinct()
                        ->orderBy('event_type')
                        ->pluck('event_type', 'event_type')
                        ->all()),
                Tables\Filters\SelectFilter::make('response_status')
                    ->label('HTTP outcome')
                    ->options([
                        '2xx' => '2xx — accepted',
                        '4xx' => '4xx — rejected',
                        '5xx' => '5xx — handler error',
                    ])
                    ->query(function ($query, array $data) {
                        $value = $data['value'] ?? null;
                        return match ($value) {
                            '2xx' => $query->whereBetween('response_status', [200, 299]),
                            '4xx' => $query->whereBetween('response_status', [400, 499]),
                            '5xx' => $query->whereBetween('response_status', [500, 599]),
                            default => $query,
                        };
                    }),
                Tables\Filters\TernaryFilter::make('error_message')
                    ->label('Has error')
                    ->nullable(),
            ])
            ->recordActions([
                Action::make('viewError')
                    ->label('View error')
                    ->icon('heroicon-o-exclamation-circle')
                    ->color('danger')
                    ->visible(fn (PelicanProcessedEvent $record): bool => ! empty($record->error_message))
                    ->modalHeading('Handler error')
                    ->modalContent(fn (PelicanProcessedEvent $record): HtmlString => new HtmlString(
                        '<pre class="text-xs bg-gray-50 dark:bg-gray-900 p-4 rounded-md overflow-auto max-h-[60vh] whitespace-pre-wrap break-all">'
                        . e((string) $record->error_message)
                        . '</pre>'
                    ))
                    ->modalSubmitAction(false)
                    ->modalCancelActionLabel('Close'),
            ])
            ->toolbarActions([])
            ->defaultSort('processed_at', 'desc')
            ->emptyStateIcon('heroicon-o-bolt')
            ->emptyStateHeading(__('admin.resources.pelican_webhook_logs.plural'))
            ->emptyStateDescription(__('admin.common.empty_states.logs'));
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListPelicanWebhookLogs::route('/'),
        ];
    }
}
